Repository AY2223S1-CS2103T-T08-3/tp, pull requests merged in 2022-10, with the labels that each got.

#50 Add Occupation to Person class
  src/main/java/seedu/address/logic/commands/AddAddressCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Occupation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, type.Enhancement, type.Task, type.Bug, priority.High

#44 Add sort command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/sort/EmailComparator.java
  src/main/java/seedu/address/model/sort/NameComparator.java
  src/main/java/seedu/address/model/sort/PhoneComparator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: type.Story, priority.High

#61 Occupation GUI
  docs/index.md
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Story, type.Task, type.Bug, priority.High

#81 Use web safe font in HelpWindow
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#83 Update DG
  docs/DeveloperGuide.md
  docs/images/CreateGroupSequenceDiagram.png
Labels: type.Task, priority.Medium

#85 Update DG
  docs/DeveloperGuide.md
Labels: severity.Medium, type.Bug

#87 Update DG for HistoryCommand
  docs/DeveloperGuide.md
  docs/diagrams/HistorySequenceDiagram.puml
  docs/images/HistorySequenceDiagram.png
Labels: severity.Medium, type.Task, priority.High

#93 Add HistoryCommand & some tests
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/storage/HistoryList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
Labels: priority.Medium

#95 Add OpenCommand
  src/main/java/seedu/address/logic/commands/IncludeCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
Labels: type.Epic, type.Enhancement, type.Task, priority.High

#96 Update GUI for Socials
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/model/social/Social.java
  src/main/java/seedu/address/model/social/exceptions/SocialException.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#99 Fix bug regarding valid links
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/model/social/Social.java
Labels: type.Enhancement, type.Task, type.Bug

#98 Add group feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddAddressCommand.java
  src/main/java/seedu/address/logic/commands/AddToGroupCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/UngroupCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UngroupCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/IsPersonInGroup.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/GroupWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/GroupWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#101 Update Socials and GUI
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/social/Social.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/button.css
Labels: type.Enhancement, type.Task, type.Bug, priority.Low

#102 Update UG with addtogroup feature
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#103 Add Social Command (Filter preferred socials)
  src/main/java/seedu/address/logic/commands/SocialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SocialCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsSocial.java
  src/main/java/seedu/address/package.json
  src/test/java/seedu/address/logic/commands/SocialCommandTest.java
Labels: type.Story, type.Enhancement, priority.High

#104 Add group feature
  src/main/java/seedu/address/ui/GroupWindow.java
  src/main/resources/view/GroupWindow.fxml
Labels: type.Enhancement, priority.Medium

#105 Add emailall command
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EmailAllCommandParser.java
Labels: type.Story, priority.Medium

#106 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#107 add Profile Picture
  build.gradle
  json-simple-1.1.1.jar
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/social/Social.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/PictureStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/json-simple-1.1.1.jar
  src/main/resources/images/profile_pic.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Story, type.Enhancement, priority.Medium

#108 Add favorite command ('fav')
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddToFavCommand.java
  src/main/java/seedu/address/logic/commands/AddToGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddToFavCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Enhancement, priority.Medium

#111 Update PictureStorage.java
  src/main/java/seedu/address/storage/PictureStorage.java
Labels: severity.Medium, type.Bug

#112 Fix GUI bugs
  src/main/java/seedu/address/logic/commands/ExcludeCommand.java
  src/main/java/seedu/address/logic/commands/IncludeCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/PreferCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/social/Social.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, type.Bug, priority.High

#118 bug profilepicfix
  json-simple-1.1.1.jar
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/json-simple-1.1.1.jar
  src/main/resources/view/PersonListCard.fxml
Labels: severity.High, type.Bug

#124 Update GUI and UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/IncludeCommand.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/GroupWindow.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement, type.Bug, priority.Medium

#127 Fix Bug relating to duplicate person.
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: severity.High, type.Enhancement, type.Task, type.Bug

#128 Update HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Low
