Repository AY2223S1-CS2103T-T08-3/tp, pull requests merged in 2022-11, with the labels that each got.

#186 Update error message for EmailAll
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
Labels: type.Bug, priority.Low

#188 Fix HelpCommand typo
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.Low

#189 Fix AddToGroup error message
  src/main/java/seedu/address/logic/commands/AddToGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/UngroupCommandParser.java
Labels: type.Bug, priority.Low

#191 Branch bugfix profile pic
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/social/Social.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/PictureStorage.java
  src/main/java/seedu/address/storage/PictureStorageLoader.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/default_pic.png
  src/main/resources/images/professor_pic.png
  src/main/resources/images/student_pic.png
  src/main/resources/images/ta_pic.png
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: severity.Medium, type.Bug

#193 Add testcases for EmailAllCommand
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/test/java/seedu/address/logic/commands/EmailAllCommandTest.java
Labels: type.Task, priority.High

#194 Update jsincorporated.md
  docs/team/jsincorporated.md
Labels: type.Task, priority.Medium

#196 Update jnwkm.md
  docs/team/jnwkm.md
Labels: priority.Medium

#199 Fix Checkstyle issues
  src/main/java/seedu/address/logic/commands/IncludeCommand.java
  src/main/java/seedu/address/model/social/Social.java
Labels: type.Task, type.Bug, priority.High

#195 Update liviamil.md
  docs/team/liviamil.md
Labels: type.Task, priority.Medium

#201 Update HelpWindow picture
  docs/images/helpMessage.png
Labels: type.Task, priority.Medium

#202 Add pictures for EmailAll in UserGuide.md
  docs/UserGuide.md
  docs/images/EmailAllExample1.png
  docs/images/EmailAllExample2.png
Labels: type.Task, priority.Medium

#203 Update picture for EmailAll in UserGuide.md
  docs/UserGuide.md
  docs/images/EmailAllExample2.png
Labels: type.Task, priority.Medium

#204 Update UG
  docs/UserGuide.md
  docs/images/EmailAllExample2.png
  docs/images/GroupCommandExample.png
Labels: type.Task, priority.Medium

#205 Branch add history feature tests
  build.gradle
  docs/UserGuide.md
  docs/team/jnwkm.md
  src/main/java/seedu/address/storage/HistoryList.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/storage/HistoryListTest.java
Labels: type.Task, priority.Medium

#206 Update jnwkm.md
  docs/team/jnwkm.md
Labels: type.Task, priority.Medium

#207 Added Tests for Occupation
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/OccupationTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#208 add PictureStorageLoaderTests
  src/main/java/seedu/address/storage/PictureStorageLoader.java
  src/test/java/seedu/address/storage/PictureStorageLoaderTest.java
Labels: type.Task, priority.Medium

#210 More Tests
  src/main/java/seedu/address/model/social/Social.java
  src/test/java/seedu/address/logic/commands/IncludeCommandTest.java
  src/test/java/seedu/address/model/person/SocialTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#211 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddToGroupSequenceDiagram.puml
  docs/images/AddToGroupSequenceDiagram.png
  docs/images/CreateGroupSequenceDiagram.png
Labels: type.Task, priority.Medium

#212 Update DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Low

#213 Update PPP
  docs/AboutUs.md
  docs/team/jsincorporated.md
Labels: type.Task, priority.Medium

#214 Fix DG diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SocialMediaAddSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/SocialMediaAddSequenceDiagram.png
Labels: type.Enhancement, type.Task, priority.High

#215 Update DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, type.Task, priority.High

#223 Update DG with use cases and manual test examples
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.Medium

#224 Update jsincorporated.md
  docs/team/jsincorporated.md
Labels: type.Task, priority.Medium

#226 Branch undoable1
  src/main/java/seedu/address/logic/commands/AddAddressCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddToFavCommand.java
  src/main/java/seedu/address/logic/commands/AddToGroupCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/IncludeCommand.java
  src/main/java/seedu/address/logic/commands/PreferCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UngroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/HistoryList.java
Labels: severity.Medium, type.Bug

#228 Add parser tests and fix EditCommand bugs
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/social/Social.java
  src/test/java/seedu/address/logic/commands/SocialTestUtil.java
  src/test/java/seedu/address/logic/parser/ExcludeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IncludeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OpenCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PreferCommandParserTest.java
Labels: type.Task, type.Bug, priority.Medium

#230 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.Medium

#231 Branch character limit
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Bug

#242 Update jsincorporated.md
  docs/team/jsincorporated.md
Labels: type.Task, priority.Medium

#241 Update UGDG and turretdive.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/turretdive.md
Labels: type.Task
